######################################################################
# Automatically generated by qmake (3.0) ?? ???. 6 12:00:54 2018
######################################################################

TEMPLATE = app
TARGET = MyServer
INCLUDEPATH += .

# Input
HEADERS += myserver.h
SOURCES += main.cpp \
    myserver.cpp
QT += widgets\
      core\
      network\
      xml
CONFIG +=c++11

DISTFILES += \
    readme.txt \
    aboutStruct.txt
